/*
    AUTOGENERATED FILE, DO NOT MODIFY
*/

module;

#include <stormkit/core/platform_macro.hpp>
#include <stormkit/core/flags_macro.hpp>

#include <stormkit/gpu/api.hpp>
#include <stormkit/gpu/vulkan.hpp>

export module stormkit.gpu.core:vulkan.enums;

import std;
import stormkit.core;
import stormkit.image;

import :vulkan.volk;
{%
import("core.base.json")
local json_data = json.loadfile("modules/stormkit/gpu/core/vulkan/mapping.json")
%}

export {
    namespace stormkit::gpu {
        namespace details {
            template <meta::IsEnumeration>
            inline constexpr auto IS_VULKAN_ENUMERATION = false;
        }

        namespace meta {
            template<typename T>
            concept IsVulkanEnumeration = core::meta::IsEnumeration<T> and details::IS_VULKAN_ENUMERATION<T>;
        }

        inline constexpr auto QUEUE_FAMILY_IGNORED = std::numeric_limits<u32>::max();
        {% for name, enumeration in table.orderpairs(json_data) do %}
        enum class {% outfile:write(name) %} : {% outfile:write(enumeration["type"]) %} {
           {% for val_name, value in table.orderpairs(enumeration["values"]) do outfile:write(val_name) %} = {% outfile:write(value["vulkan"]) %},
           {% end %}
        };

        template <>
        inline constexpr auto details::IS_VULKAN_ENUMERATION<{% outfile:write(name) %}> = true;
        {% end %}

        namespace vk {
            template<typename T = VkFlags, meta::IsVulkanEnumeration U>
                requires(core::meta::IsPlainEnumeration<T> or core::meta::Is<T, VkFlags>)
            [[nodiscard]]
            constexpr auto to_vk(U value) noexcept -> T;

            template<meta::IsVulkanEnumeration T, typename U>
                requires(core::meta::IsPlainEnumeration<U> or core::meta::Is<U, VkFlags>)
            [[nodiscard]]
            constexpr auto from_vk(U value) noexcept -> T;
        }

        [[nodiscard]]
        constexpr auto from_image(image::Image::Format format) -> PixelFormat;
    
        [[nodiscard]]
        constexpr auto is_depth_only_format(PixelFormat format) noexcept -> bool;
        [[nodiscard]]
        constexpr auto is_stencil_only_format(PixelFormat format) noexcept -> bool;
        [[nodiscard]]
        constexpr auto is_depth_stencil_format(PixelFormat format) noexcept -> bool;
        [[nodiscard]]
        constexpr auto is_depth_format(PixelFormat format) noexcept -> bool;
        [[nodiscard]]
        constexpr auto is_stencil_format(PixelFormat format) noexcept -> bool;

        [[nodiscard]]
        constexpr auto get_format_channel_count(PixelFormat format) noexcept -> u8;
        [[nodiscard]]
        constexpr auto get_format_element_count(PixelFormat format) noexcept -> u8;
    }
    {% for name, enumeration in table.orderpairs(json_data) do %}FLAG_ENUM(stormkit::gpu::{% outfile:write(name) %})
    template<>
    STORMKIT_FORCE_INLINE
    STORMKIT_CONST
    constexpr auto stormkit::core::meta::enumerate<stormkit::gpu::{% outfile:write(name) %}>() noexcept -> decltype(auto) {
        return array {
           {% for val_name, value in table.orderpairs(enumeration["values"]) do %}stormkit::gpu::{% outfile:write(name) %}::{% outfile:write(val_name) %},
           {% end %}
        };
    }
    template<>
    STORMKIT_FORCE_INLINE
    STORMKIT_CONST
    constexpr auto stormkit::core::as_string<stormkit::gpu::{% outfile:write(name) %}>(stormkit::gpu::{% outfile:write(name) %} value) noexcept -> string_view {
        switch(value) {
           {% for val_name, value in table.orderpairs(enumeration["values"]) do %}case stormkit::gpu::{% outfile:write(name) %}::{% outfile:write(val_name) %}: return "{%  outfile:write(name) %}::{% outfile:write(val_name) %}";
           {% end %}
        }
        std::unreachable();
    }
    template<>
    STORMKIT_FORCE_INLINE
    constexpr auto stormkit::core::to_string<stormkit::gpu::{% outfile:write(name) %}>(stormkit::gpu::{% outfile:write(name) %} value) noexcept -> string {
        switch(value) {
           {% for val_name, value in table.orderpairs(enumeration["values"]) do %}case stormkit::gpu::{% outfile:write(name) %}::{% outfile:write(val_name) %}: return "{%  outfile:write(name) %}::{% outfile:write(val_name) %}";
           {% end %}
        }
        std::unreachable();
    }
    {% end %}
}

////////////////////////////////////////////////////////////////////
///                      IMPLEMENTATION                          ///
////////////////////////////////////////////////////////////////////

namespace stormkit::gpu {
    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto is_depth_only_format(PixelFormat format) noexcept -> bool {
        return format == PixelFormat::DEPTH16_UNORM
               or format == PixelFormat::DEPTH24_UNORM_PACK32
               or format == PixelFormat::DEPTH32F;
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto is_stencil_only_format(PixelFormat format) noexcept -> bool {
        return format == PixelFormat::S8U;
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto is_depth_stencil_format(PixelFormat format) noexcept -> bool {
        return format == PixelFormat::DEPTH16_UNORM_STENCIL8U
               or format == PixelFormat::DEPTH24_UNORM_STENCIL8U
               or format == PixelFormat::DEPTH32F_STENCIL8U;
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto is_depth_format(PixelFormat format) noexcept -> bool {
        return is_depth_only_format(format) or is_depth_stencil_format(format);
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto is_stencil_format(PixelFormat format) noexcept -> bool {
        return is_stencil_only_format(format) or is_depth_stencil_format(format);
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto get_format_channel_count(PixelFormat format) noexcept -> u8 {
        switch (format) {
            case PixelFormat::R8_SNORM:
            case PixelFormat::R8_UNORM:
            case PixelFormat::R16_SNORM:
            case PixelFormat::R16_UNORM:
            case PixelFormat::R8I:
            case PixelFormat::R8U:
            case PixelFormat::R16I:
            case PixelFormat::R16U:
            case PixelFormat::R32I:
            case PixelFormat::R32U:
            case PixelFormat::R16F:
            case PixelFormat::R32F:
            case PixelFormat::DEPTH16_UNORM:
            case PixelFormat::DEPTH24_UNORM_PACK32:
            case PixelFormat::DEPTH32F: return 1;

            case PixelFormat::RG8_SNORM:
            case PixelFormat::RG8_UNORM:
            case PixelFormat::RG16_SNORM:
            case PixelFormat::RG16_UNORM:
            case PixelFormat::RG8I:
            case PixelFormat::RG8U:
            case PixelFormat::RG16I:
            case PixelFormat::RG16U:
            case PixelFormat::RG32I:
            case PixelFormat::RG32U:
            case PixelFormat::RG16F:
            case PixelFormat::RG32F:
            case PixelFormat::DEPTH16_UNORM_STENCIL8U:
            case PixelFormat::DEPTH24_UNORM_STENCIL8U:
            case PixelFormat::DEPTH32F_STENCIL8U: return 2;

            case PixelFormat::RGB8_SNORM:
            case PixelFormat::RGB8_UNORM:
            case PixelFormat::RGB16_SNORM:
            case PixelFormat::RGB16_UNORM:
            case PixelFormat::BGR8_UNORM:
            case PixelFormat::RGB8I:
            case PixelFormat::RGB8U:
            case PixelFormat::RGB16I:
            case PixelFormat::RGB16U:
            case PixelFormat::RGB32I:
            case PixelFormat::RGB32U:
            case PixelFormat::RGB16F:
            case PixelFormat::RGB32F:
            case PixelFormat::SRGB8:
            case PixelFormat::SBGR8:
            case PixelFormat::R5_G6_B5_UNORM_PACK16:
            case PixelFormat::B10_GR11UF_PACK32: return 3;

            case PixelFormat::RGBA8_SNORM:
            case PixelFormat::RGBA8_UNORM:
            case PixelFormat::RGBA16_SNORM:
            case PixelFormat::RGBA16_UNORM:
            case PixelFormat::BGRA8_UNORM:
            case PixelFormat::RGBA8I:
            case PixelFormat::RGBA8U:
            case PixelFormat::RGBA16I:
            case PixelFormat::RGBA16U:
            case PixelFormat::RGBA32I:
            case PixelFormat::RGBA32U:
            case PixelFormat::RGBA16F:
            case PixelFormat::RGBA32F:
            case PixelFormat::SRGBA8:
            case PixelFormat::SBGRA8: return 4;

            default: break;
        }

        return 0u;
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto get_format_element_count(PixelFormat format) noexcept -> u8 {
        switch (format) {
            case PixelFormat::R8_SNORM:
            case PixelFormat::R8_UNORM:
            case PixelFormat::RG8_SNORM:
            case PixelFormat::RG8_UNORM:
            case PixelFormat::R8I:
            case PixelFormat::R8U:
            case PixelFormat::RG8I:
            case PixelFormat::RG8U:
            case PixelFormat::RGB8_SNORM:
            case PixelFormat::RGB8_UNORM:
            case PixelFormat::BGR8_UNORM:
            case PixelFormat::RGB8I:
            case PixelFormat::RGB8U:
            case PixelFormat::RGBA8_SNORM:
            case PixelFormat::RGBA8_UNORM:
            case PixelFormat::RGBA16_SNORM:
            case PixelFormat::BGRA8_UNORM:
            case PixelFormat::SRGB8:
            case PixelFormat::SBGR8:
            case PixelFormat::SRGBA8:
            case PixelFormat::SBGRA8: return 1u;

            case PixelFormat::R16_SNORM:
            case PixelFormat::R16_UNORM:
            case PixelFormat::R16I:
            case PixelFormat::R16U:
            case PixelFormat::RG16_SNORM:
            case PixelFormat::RG16_UNORM:
            case PixelFormat::RG16I:
            case PixelFormat::RG16U:
            case PixelFormat::RG16F:
            case PixelFormat::RGB16I:
            case PixelFormat::RGB16U:
            case PixelFormat::RGB16F:
            case PixelFormat::RGBA16I:
            case PixelFormat::RGBA16U:
            case PixelFormat::RGBA16F:
            case PixelFormat::R16F: return 2u;

            case PixelFormat::R32I:
            case PixelFormat::R32U:
            case PixelFormat::R32F:
            case PixelFormat::RG32I:
            case PixelFormat::RG32U:
            case PixelFormat::RG32F:
            case PixelFormat::RGB16_SNORM:
            case PixelFormat::RGB32I:
            case PixelFormat::RGB32U:
            case PixelFormat::RGB32F:
            case PixelFormat::RGBA8I:
            case PixelFormat::RGBA8U:
            case PixelFormat::RGBA32I:
            case PixelFormat::RGBA32U:
            case PixelFormat::RGBA32F: return 4u;

            default: break;
        }

        return 0u;
    }

    namespace vk {
        /////////////////////////////////////
        /////////////////////////////////////
        template<typename T = VkFlags, meta::IsVulkanEnumeration U>
            requires(core::meta::IsPlainEnumeration<T> or core::meta::Is<T, VkFlags>)
        STORMKIT_FORCE_INLINE
    	STORMKIT_CONST
        STORMKIT_INTRINSIC
        constexpr auto to_vk(U value) noexcept -> T{
            return narrow<T>(value);
        }

        /////////////////////////////////////
        /////////////////////////////////////
        template<meta::IsVulkanEnumeration T, typename U>
            requires(core::meta::IsPlainEnumeration<U> or core::meta::Is<U, VkFlags>)
        STORMKIT_FORCE_INLINE
    	STORMKIT_CONST
        STORMKIT_INTRINSIC
        constexpr auto from_vk(U value) noexcept -> T {
            return narrow<T>(value);
        }
    }

    /////////////////////////////////////
    /////////////////////////////////////
    STORMKIT_FORCE_INLINE
	STORMKIT_CONST
    constexpr auto from_image(image::Image::Format format) -> PixelFormat {
        switch(format) {
            case image::Image::Format::R8_SNORM     : return PixelFormat::R8_SNORM     ;
            case image::Image::Format::RG8_SNORM    : return PixelFormat::RG8_SNORM    ;
            case image::Image::Format::RGB8_SNORM   : return PixelFormat::RGB8_SNORM   ;
            case image::Image::Format::RGBA8_SNORM  : return PixelFormat::RGBA8_SNORM  ;
            case image::Image::Format::R8_UNORM     : return PixelFormat::R8_UNORM     ;
            case image::Image::Format::RG8_UNORM    : return PixelFormat::RG8_UNORM    ;
            case image::Image::Format::RGB8_UNORM   : return PixelFormat::RGB8_UNORM   ;
            case image::Image::Format::RGBA8_UNORM  : return PixelFormat::RGBA8_UNORM  ;
            case image::Image::Format::R16_SNORM    : return PixelFormat::R16_SNORM    ;
            case image::Image::Format::RG16_SNORM   : return PixelFormat::RG16_SNORM   ;
            case image::Image::Format::RGB16_SNORM  : return PixelFormat::RGB16_SNORM  ;
            case image::Image::Format::RGBA16_SNORM : return PixelFormat::RGBA16_SNORM ;
            case image::Image::Format::R16_UNORM    : return PixelFormat::R16_UNORM    ;
            case image::Image::Format::RG16_UNORM   : return PixelFormat::RG16_UNORM   ;
            case image::Image::Format::RGB16_UNORM  : return PixelFormat::RGB16_UNORM  ;
            case image::Image::Format::RGBA16_UNORM : return PixelFormat::RGBA16_UNORM ;
            case image::Image::Format::RGBA4_UNORM  : return PixelFormat::RGBA4_UNORM_PACK16 ;
            case image::Image::Format::BGR8_UNORM   : return PixelFormat::BGR8_UNORM   ;
            case image::Image::Format::BGRA8_UNORM  : return PixelFormat::BGRA8_UNORM  ;
            case image::Image::Format::R8I          : return PixelFormat::R8I          ;
            case image::Image::Format::RG8I         : return PixelFormat::RG8I         ;
            case image::Image::Format::RGB8I        : return PixelFormat::RGB8I        ;
            case image::Image::Format::RGBA8I       : return PixelFormat::RGBA8I       ;
            case image::Image::Format::R8U          : return PixelFormat::R8U          ;
            case image::Image::Format::RG8U         : return PixelFormat::RG8U         ;
            case image::Image::Format::RGB8U        : return PixelFormat::RGB8U        ;
            case image::Image::Format::RGBA8U       : return PixelFormat::RGBA8U       ;
            case image::Image::Format::R16I         : return PixelFormat::R16I         ;
            case image::Image::Format::RG16I        : return PixelFormat::RG16I        ;
            case image::Image::Format::RGB16I       : return PixelFormat::RGB16I       ;
            case image::Image::Format::RGBA16I      : return PixelFormat::RGBA16I      ;
            case image::Image::Format::R16U         : return PixelFormat::R16U         ;
            case image::Image::Format::RG16U        : return PixelFormat::RG16U        ;
            case image::Image::Format::RGB16U       : return PixelFormat::RGB16U       ;
            case image::Image::Format::RGBA16U      : return PixelFormat::RGBA16U      ;
            case image::Image::Format::R32I         : return PixelFormat::R32I         ;
            case image::Image::Format::RG32I        : return PixelFormat::RG32I        ;
            case image::Image::Format::RGB32I       : return PixelFormat::RGB32I       ;
            case image::Image::Format::RGBA32I      : return PixelFormat::RGBA32I      ;
            case image::Image::Format::R32U         : return PixelFormat::R32U         ;
            case image::Image::Format::RG32U        : return PixelFormat::RG32U        ;
            case image::Image::Format::RGB32U       : return PixelFormat::RGB32U       ;
            case image::Image::Format::RGBA32U      : return PixelFormat::RGBA32U      ;
            case image::Image::Format::R16F         : return PixelFormat::R16F         ;
            case image::Image::Format::RG16F        : return PixelFormat::RG16F        ;
            case image::Image::Format::RGB16F       : return PixelFormat::RGB16F       ;
            case image::Image::Format::RGBA16F      : return PixelFormat::RGBA16F      ;
            case image::Image::Format::R32F         : return PixelFormat::R32F         ;
            case image::Image::Format::RG32F        : return PixelFormat::RG32F        ;
            case image::Image::Format::RGB32F       : return PixelFormat::RGB32F       ;
            case image::Image::Format::RGBA32F      : return PixelFormat::RGBA32F      ;
            case image::Image::Format::SRGB8        : return PixelFormat::SRGB8        ;
            case image::Image::Format::SRGBA8       : return PixelFormat::SRGBA8       ;
            case image::Image::Format::SBGR8        : return PixelFormat::SBGR8        ;
            case image::Image::Format::SBGRA8       : return PixelFormat::SBGRA8       ;
            case image::Image::Format::UNDEFINED    : return PixelFormat::UNDEFINED    ;

            default: break;
        }

        std::unreachable();
    }
}

#ifndef STORMKIT_OS_WINDOWS
    #undef STORMKIT_GPU_API
    #define STORMKIT_GPU_API
#endif

{% for name, enumeration in table.orderpairs(json_data) do %}
    template
    stormkit::gpu::{% outfile:write(name) %} STORMKIT_GPU_API stormkit::gpu::vk::from_vk<stormkit::gpu::{% outfile:write(name) %}, VkFlags>(VkFlags);
    template
    stormkit::gpu::{% outfile:write(name) %} STORMKIT_GPU_API stormkit::gpu::vk::from_vk<stormkit::gpu::{% outfile:write(name) %}, {% outfile:write(enumeration.vktype) %}>({% outfile:write(enumeration.vktype) %});
    template
    VkFlags STORMKIT_GPU_API stormkit::gpu::vk::to_vk<VkFlags>(stormkit::gpu::{% outfile:write(name) %});
    template
    {% outfile:write(enumeration.vktype) %} STORMKIT_GPU_API stormkit::gpu::vk::to_vk<{% outfile:write(enumeration.vktype) %}>(stormkit::gpu::{% outfile:write(name) %});
{% end %}
