set(CMAKE_IMPORT_FILE_VERSION 1)

get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

if(UNIX)
    get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
endif()

if(APPLE)
  set(_IMPORT_PREFIX "/usr/local")
endif()

if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

set(CORE_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-core-static.a")

set_target_properties(StormKit::Core PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${CORE_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Core)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Core ${CORE_LIB_NAME})

set(ENGINE_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-engine-static.a")

set_target_properties(StormKit::Engine PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${ENGINE_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Engine)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Engine ${ENGINE_LIB_NAME})

set(ENTITIES_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-entities-static.a")

set_target_properties(StormKit::Entities PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${ENGINE_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Entities)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Entities ${ENTITIES_LIB_NAME})

set(IMAGE_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-image-static.a")

set_target_properties(StormKit::Image PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${IMAGE_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Image)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Image ${IMAGE_LIB_NAME})

set(LOG_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-log-static.a")

set_target_properties(StormKit::Log PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${LOG_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Log)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Log ${LOG_LIB_NAME})

set(MAIN_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-main.a")

set_target_properties(StormKit::Main PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${MAIN_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Main)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Main ${MAIN_LIB_NAME})

set(MODULE_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-module-static.a")

set_target_properties(StormKit::Module PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${MODULE_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Module)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Module ${MODULE_LIB_NAME})

set(RENDER_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-render-static.a")

set_target_properties(StormKit::Render PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${RENDER_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Render)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Render ${RENDER_LIB_NAME})

set(WINDOW_LIB_NAME "${_IMPORT_PREFIX}/lib/libStormKit-window-static.a")

set_target_properties(StormKit::Window PROPERTIES
  IMPORTED_CONFIGURATIONS RELEASE
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE ${WINDOW_LIB_NAME}
)

list(APPEND _IMPORT_CHECK_TARGETS StormKit::Window)
list(APPEND _IMPORT_CHECK_FILES_FOR_StormKit::Window ${WINDOW_LIB_NAME})

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
