// Copyright (C) 2023 Arthur LAURENT <arthur.laurent4@gmail.com>
// This file is subject to the license terms in the LICENSE file
// found in the top-level of this distribution
export namespace stormkit::core {
    using Hash32 = std::uint32_t;
    using Hash64 = std::uint64_t;

    template<class T>
    concept HashValue = core::IsOneOf<T, Hash32, Hash64>;

    template<HashValue OutputType = Hash32>
    constexpr auto hashCombine(auto&& value) -> OutputType;

    constexpr auto hashCombine(HashValue auto& hash, IsHashable auto&& v) noexcept;

    constexpr auto hashCombine(HashValue auto& hash, std::ranges::range auto&& range) noexcept;

    template<typename... Args>
    constexpr auto hashCombine(HashValue auto& hash, Args&&... args) noexcept;
} // namespace stormkit::core

////////////////////////////////////////////////////////////////////
///                      IMPLEMENTATION                          ///
////////////////////////////////////////////////////////////////////

namespace stormkit::core {
    template<HashValue OutputType>
    constexpr auto hashCombine(auto&& value) -> OutputType {
        auto hash = OutputType { 0u };

        hashCombine(hash, std::forward<decltype(value)>(value));

        return hash;
    }

    constexpr auto hashCombine(HashValue auto& hash, IsHashable auto&& value) noexcept {
        const auto hasher = std::hash<std::remove_cvref_t<decltype(value)>> {};
        hash ^=
            hasher(std::forward<decltype(value)>(value)) + 0x9e3779b9 + (hash << 6) + (hash >> 2);
    }

    constexpr auto hashCombine(HashValue auto& hash, std::ranges::range auto&& range) noexcept {
        for (auto&& value : range) hashCombine(hash, std::forward<decltype(value)>(value));
    }

    template<typename... Args>
    constexpr auto hashCombine(HashValue auto& hash, Args&&... args) noexcept {
        (hashCombine(hash, std::forward<Args>(args)), ...);
    }
} // namespace stormkit::core
