name: Android

on:
  push:
    branches: [  ]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '**.m'
      - '**.swift'
      - .github/workflows/**.yml
      - '!.github/workflows/android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [  ]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '**.m'
      - '**.swift'
      - .github/workflows/**.yml
      - '!.github/workflows/android.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: Android-${{ matrix.arch }} ( ${{ matrix.kind }}-${{ matrix.mode }} )

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]
        mode: [release, debug, asan]
        arch: [armeabi-v7a, arm64-v8a]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Android-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Update xmake repository
        run: xmake repo --update

      - name: Prepare
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q -o ./android-ndk-r25b-linux.zip

      - name: Configure & Build
        id: build
        run: |
          xmake f -D --yes -a ${{ matrix.arch }} -p android --ndk=`pwd`/android-ndk-r25b --ndk_sdkver=33 -m ${{ matrix.mode }} -k ${{ matrix.kind }}
          xmake b -D

      - name: Installation
        run: xmake install -D --installdir="${{ runner.workspace }}/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v1
        with:
          name: Android-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}
          path: ${{ runner.workspace }}/output
