---
name: linux

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - '**.m'
      - '**.swift'
      - .github/workflows/*.yml
      - '!.github/workflows/linux.yml'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches: [main, develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - '**.m'
      - '**.swift'
      - .github/workflows/**.yml
      - '!.github/workflows/linux.yml'
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: ${{ matrix.compiler }}-${{ matrix.cpplib }} ${{ matrix.arch }}  (${{ matrix.kind }}/${{ matrix.mode }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04]
        compiler: [llvm]
        cpplib: [libc++]
        arch: [x64]
        kind: [static, shared]
        mode: [releasedbg, debug]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.compiler }}-${{ matrix.cpplib }}-${{ matrix.arch }}${{ matrix.kind }}-${{ matrix.mode }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Bootstrap
        id: bootstrap
        uses: ./.github/actions/setup
        with:
          os: linux
          arch: matrix.arch
          compiler: matrix.compiler

      - run: ls ${{ runner.workspace }}/.github/actions

      - name: Build & Tests
        id: build_and_tests
        uses: ./.github/actions/build
        with:
          os: linux
          arch: matrix.arch
          compiler: matrix.compiler
          cpplib: matrix.cpplib
          mode: matrix.mode
          kind: matrix.kind
          dep_hash: matrix.dep_hash
          cache_key: matrix.cache_key
          additional_flags: |
            ${{ (matrix.compiler == 'llvm' && matrix.cpplib == 'libc++') && '--sdk="/usr/lib/llvm-$LLVM_VERSION"' || '' }} \
            ${{ (matrix.compiler == 'llvm' && matrix.cpplib == 'libc++') && '--ldflags="-fuse-ld=lld -L/usr/lib/llvm-$LLVM_VERSION/lib/ -lc++abi" --shflags="-fuse-ld=lld -L/usr/lib/llvm-$LLVM_VERSION/lib/ -lc++abi"' || '' }} \
            ${{ (matrix.cpplib == 'libc++') && '--runtimes="c++_static"' || '' }}

      - name: Upload artifacts
        id: upload
        uses: ./.github/actions/upload
        with:
          name: Linux-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.cpplib }}-${{ matrix.kind }}-${{ matrix.mode }}

