---
name: macos

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/ios/**.m'
      - '.src/*/ios/**.swift'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - .github/workflows/**.yml
      - '!.github/workflows/macos.yml'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches: [main, develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/ios/**.m'
      - '.src/*/ios/**.swift'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - .github/workflows/**.yml
      - '!.github/workflows/macos.yml'
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: ${{ matrix.compiler }} ${{ matrix.arch }}  (${{ matrix.kind }}/${{ matrix.mode }})
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-26]
        compiler: [llvm]
        arch: [arm64]
        kind: [static, shared]
        mode: [release, debug]

    runs-on: ${{ matrix.os }}${{ (matrix.arch == 'x64') && '-large' || '' }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    concurrency:
      group:
        ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.arch }}-${{ matrix.kind }}-${{ matrix.mode }}

    steps:
      - name: Use current date as xmake package cache key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Install build tools
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: llvm ninja meson cmake mold nasm pkgconf
          verbose: true

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set XMake env
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

      - name: Update XMake repository
        run: xmake repo --update

      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT
      
      - name: Restore cached packages
        id: restore-depcache
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

      - name: Configure & Install dependencies
        id: configure
        run: |
          xmake f \
           --mode=${{ matrix.mode }} \
           --kind=${{ matrix.kind }} \
           --examples=y \
           --tests=y \
           --sanitizers=n \
           --mold=y \
           --on_ci=y \
           --lto=${{ (matrix.mode == 'release') && 'y' || 'n' }} \
           --toolchain=llvm \
           --sdk="$(brew --prefix llvm)" \
           --sc="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend" \
           --runtimes="c++_static" \
           --yes

      - name: Cache xmake dependencies
        if: ${{ !steps.restore-depcache.outputs.cache-hit }}
        uses: actions/cache/save@v6
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ steps.restore-depcache.outputs.cache-primary-key }}

      - name: Build
        id: build
        run: |
          xmake b

      - name: Run unit tests
        id: tests
        run: xmake test -v

      - name: Installation
        id: install
        run: xmake install -v --installdir="${{ runner.workspace }}/output"

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.kind }}-${{ matrix.mode }}
          path: ${{ runner.workspace }}/output
