---
name: macos

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/ios/**.m'
      - '.src/*/ios/**.swift'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - .github/workflows/**.yml
      - '!.github/workflows/macos.yml'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches: [main, develop]
    paths-ignore:
      - '.src/*/win32/**.cppm'
      - '.src/*/win32/**.c'
      - '.src/*/win32/**.cpp'
      - '.src/*/win32/**.h'
      - '.src/*/win32/**.hpp'
      - '.src/*/ios/**.m'
      - '.src/*/ios/**.swift'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - .github/workflows/**.yml
      - '!.github/workflows/macos.yml'
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: ${{ matrix.compiler }} ${{ matrix.arch }}  (${{ matrix.kind }}/${{ matrix.mode }})
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-26]
        compiler: [llvm]
        cpplib: [libc++]
        arch: [arm64]
        kind: [static, shared]
        mode: [releasedbg, debug]

    runs-on: ${{ matrix.os }}${{ (matrix.arch == 'x64') && '-large' || '' }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - name: Bootstrap
        id: bootstrap
        uses: ../actions/setup
        with:
          os: matrix.os
          arch: matrix.arch
          compiler: matrix.compiler

      - name: Build & Tests
        id: build_and_tests
        uses: ../actions/build
        with:
          os: matrix.os
          arch: matrix.arch
          compiler: matrix.compiler
          cpplib: matrix.cpplib
          mode: matrix.mode
          kind: matrix.kind
          dep_hash: matrix.dep_hash
          cache_key: matrix.cache_key
          additional_flags: |
           --sdk="$(brew --prefix llvm)" \
           --sc="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend" \

      - name: Upload artifacts
        id: upload
        uses: ../actions/upload
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.kind }}-${{ matrix.mode }}
