name: windows

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - .github/workflows/**.yml
      - '!.github/workflows/windows.yml'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches: [main, develop]
    paths-ignore:
      - .github/workflows/**.yml
      - '!.github/workflows/windows.yml'
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: ${{ matrix.compiler }}-${{ matrix.cpplib }} ${{ matrix.arch }}  (${{ matrix.kind }}/${{ matrix.mode }})

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        compiler: [llvm]
        cpplib: [libc++]
        arch: [x64]
        kind: [static, shared]
        mode: [releasedbg, debug]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Bootstrap
        id: bootstrap
        uses: ./.github/actions/setup
        with:
          os: matrix.os
          arch: matrix.arch
          compiler: matrix.compiler

      - name: Build & Tests
        id: build_and_tests
        uses: ./.github/actions/build
        with:
          os: matrix.os
          arch: matrix.arch
          compiler: matrix.compiler
          cpplib: matrix.cpplib
          mode: matrix.mode
          kind: matrix.kind
          dep_hash: matrix.dep_hash
          cache_key: matrix.cache_key
          additional_flags: |
            ${{ (matrix.compiler == 'llvm') && '--sdk="$env:GITHUB_WORKSPACE/llvm/llvm"' || '' }} `
            --policies="platform.longpaths"

      - name: Upload artifacts
        id: upload
        uses: ./.github/actions/upload
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.cpplib }}-${{ matrix.kind }}-${{ matrix.mode }}
