name: windows

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - '**.m'
      - '**.swift'
      - '.github/workflows/*.yml'
      - '!.github/workflows/windows.yml'
      - .gitignore
      - LICENSE
      - README.md

  push:
    branches: [develop]
    paths-ignore:
      - '.src/*/linux/**.cppm'
      - '.src/*/linux/**.c'
      - '.src/*/linux/**.cpp'
      - '.src/*/linux/**.h'
      - '.src/*/linux/**.hpp'
      - '.src/*/darwin/**.cppm'
      - '.src/*/darwin/**.c'
      - '.src/*/darwin/**.cpp'
      - '.src/*/darwin/**.h'
      - '.src/*/darwin/**.hpp'
      - '.src/*/macos/**.cppm'
      - '.src/*/macos/**.c'
      - '.src/*/macos/**.cpp'
      - '.src/*/macos/**.h'
      - '.src/*/macos/**.hpp'
      - '.src/*/ios/**.cppm'
      - '.src/*/ios/**.c'
      - '.src/*/ios/**.cpp'
      - '.src/*/ios/**.h'
      - '.src/*/ios/**.hpp'
      - '.src/*/android/**.cppm'
      - '.src/*/android/**.c'
      - '.src/*/android/**.cpp'
      - '.src/*/android/**.h'
      - '.src/*/android/**.hpp'
      - '**.m'
      - '**.swift'
      - '.github/workflows/*.yml'
      - '!.github/workflows/windows.yml'
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    name: ${{ matrix.compiler }}-${{ matrix.cpplib }} ${{ matrix.arch }}  (${{ matrix.kind }}/${{ matrix.mode }})

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
        compiler: [llvm]
        cpplib: [libc++]
        arch: [x64]
        kind: [static, shared]
        mode: [releasedbg, debug]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.compiler }}-${{ matrix.cpplib }}-${{ matrix.arch }}${{ matrix.kind }}-${{ matrix.mode }}
      cancel-in-progress: true

    steps:
      - name: Enable git long paths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Bootstrap
        id: bootstrap
        uses: ./.github/actions/setup
        with:
          os: windows
          arch: ${{ matrix.arch }}
          compiler: ${{ matrix.compiler }}

      - name: Build & Tests
        id: build_and_tests
        uses: ./.github/actions/build
        with:
          os: windows
          arch: ${{ matrix.arch }}
          compiler: ${{ matrix.compiler }}
          cpplib: ${{ matrix.cpplib }}
          mode: ${{ matrix.mode }}
          kind: ${{ matrix.kind }}
          dep_hash: ${{ steps.bootstrap.dep_hash }}
          cache_key: ${{ steps.bootstrap.cache_key }}
          additional_flags: |
            ${{ (matrix.compiler == 'llvm') && --sdk=${runner.workspace}/llvm/llvm || '' }} \
            --policies="platform.longpaths"

      - name: Upload artifacts
        id: upload
        uses: ./.github/actions/upload
        with:
          name: Windows-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.cpplib }}-${{ matrix.kind }}-${{ matrix.mode }}
